# Generated by Django 4.1.4 on 2022-12-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daugia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionuser',
            name='allMoney',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bidderuser',
            name='allMoney',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='MemberFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2, null=True)),
                ('money', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
