# Generated by Django 4.1.4 on 2022-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daugia', '0002_auctionuser_allmoney_bidderuser_allmoney_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfeelog',
            name='nameLog',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
