# Generated by Django 4.1.4 on 2022-12-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daugia', '0005_category_sessiondate_status_subcategory_session_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_Time',
            new_name='SessionTime',
        ),
    ]
