# Generated by Django 4.1.4 on 2022-12-11 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daugia', '0006_rename_session_time_sessiontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=100, null=True)),
                ('timelive', models.IntegerField(default=1, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daugia.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daugia.auctionuser')),
            ],
        ),
    ]
