# Generated by Django 4.1.4 on 2022-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daugia', '0008_payment_result_remove_auctedproduct_timelive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
